
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.14.0

    working_directory: ~/repo

    steps:
      - checkout
      # 푸시할 떄 돌고 머지할 때 한번 더 돈다. 
      # yml : json의 확장 버전. json에서 {}뺴고 주석 사용할 수 있다. 
      # 캐시전략 : node_module을 매번 설치하지 않고 캐싱해서 사용한다. 
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - setup_remote_docker

      - run: |
          npm test
          npm run lint
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker build -t hyejineee/cd-sample:${CIRCLE_SHA1::7} .
          docker push hyejineee/cd-sample:${CIRCLE_SHA1::7}
